### ISSUE TITLE
speechly button not appearing

### ISSUE THREAD

**Issue by Aqs31** [adrianhajdin/speechly_expense_tracker_project#10]
Uncaught TypeError: Cannot read properties of undefined (reading 'div')
    at ./node_modules/@speechly/react-ui/lib/components/Info.js (Info.tsx:64:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@speechly/react-ui/lib/components/Notifications.js (Notifications.tsx:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@speechly/react-ui/lib/components/BigTranscriptContainer.js (BigTranscriptContainer.tsx:3:1)
    at options.factory (react refresh:6:1)
    
    please help

**Comment by Aqs31** [comment]
@adrianhajdin please help
